name: Python Recommend Server CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set env file
        run: |
          touch .env
          echo "${{ secrets.RECOMMEND_APPLICATION }}" >> .env
        shell: bash

      - name: Login to KakaoCloud
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GLUE_PROJECT }}
          username: ${{ secrets.ACCESS_ID }}
          password: ${{ secrets.ACCESS_SECRET }}

      - name: Build and Push Docker image to KakaoCloud
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ secrets.GLUE_PROJECT }}/glue-repository/glue-recommend:${{ github.sha }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout configuration repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIT_PROJECT }}/glue-msa-config
          token: ${{ secrets.GIT_TOKEN }}
          ref: "main"

      - name: Install yq (YAML processor)
        run: sudo snap install yq

      - name: Update image in Kubernetes deployment file
        run: |
          yq e '.spec.template.spec.containers[0].image = "${{ secrets.GLUE_PROJECT }}/glue-repository/glue-recommend:${{ github.sha }}"' ./k8s-template/recommend-deployment.yaml -i

      - name: Commit and push changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git add .
          git commit -m "[skip ci] Update recommend-deployment.yaml"
          git remote set-url origin https://${{ secrets.GIT_TOKEN }}@github.com/${{ secrets.GIT_PROJECT }}/glue-msa-config
          git push --set-upstream origin main
